version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: sequelize
    versions:
    - 6.4.0
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: sqlite3
    versions:
    - 5.0.1
